// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zOUpg1Xx9dD_XfVxERR-OI_Su8xu3TY',
    appId: '1:804355021014:android:ca8de320e050db36381177',
    messagingSenderId: '804355021014',
    projectId: 'agbarber-bc826',
    storageBucket: 'agbarber-bc826.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOanm9tGKvD4dFo9Qcl2vnCgqzOn1iYGU',
    appId: '1:804355021014:ios:ed8c5abe0e12cca8381177',
    messagingSenderId: '804355021014',
    projectId: 'agbarber-bc826',
    storageBucket: 'agbarber-bc826.firebasestorage.app',
    iosBundleId: 'com.LoSco.agbarber.prenotazionibarbiere',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfv3UKIm-bYtEbtBolqCcBPh7dKOf9HT4',
    appId: '1:804355021014:web:637961c6bff5a5de381177',
    messagingSenderId: '804355021014',
    projectId: 'agbarber-bc826',
    authDomain: 'agbarber-bc826.firebaseapp.com',
    storageBucket: 'agbarber-bc826.firebasestorage.app',
    measurementId: 'G-PMGZVVNLHM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOanm9tGKvD4dFo9Qcl2vnCgqzOn1iYGU',
    appId: '1:804355021014:ios:ed8c5abe0e12cca8381177',
    messagingSenderId: '804355021014',
    projectId: 'agbarber-bc826',
    storageBucket: 'agbarber-bc826.firebasestorage.app',
    iosBundleId: 'com.LoSco.agbarber.prenotazionibarbiere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3VHTWpD04O8ovW-C2c2OPiirpr3L9UeE',
    appId: '1:804355021014:web:dad75b1a5c419697381177',
    messagingSenderId: '804355021014',
    projectId: 'agbarber-bc826',
    authDomain: 'agbarber-bc826.firebaseapp.com',
    storageBucket: 'agbarber-bc826.firebasestorage.app',
    measurementId: 'G-FHB3HPHM7Y',
  );
}
